name: Check Commit Message

on:
  push:
    branches:
      - main

jobs:
  check-commit-message:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: List directory
      run: |
        ls -la

    - name: testing
      run: echo ${{ github.repository }} ${{ github.ref }} 

   